Optimizing a few areas (#100)
* Running the profiler to ensure big bottlenecks are being addressed earlier than later

* Update find_dependencies.cmake

Changed scope_guard component to use my personal fork until the point at which the destructor bug can be fixed.

* Setting required version of cURL

The default required version of cURL was too new for a few platforms that CI runs on, “macOS Big Sur.”  Choosing 7.50.0 at random since it’s saying it has 7.64.1.

* Specify scope_guard is using current main branch

* Removing an extraneous warning 
   Removing warning/error about unused macros:
   ```
   home/runner/work/mmotd/mmotd/common/assertion/src/throw.cpp:153:1:error: macro "__OPTIMIZE__" is not used [-Werror=unused-macros]
     153 | } // namespace mmotd::assertion
         | ^
   ```