Removing an extraneous warning
Removing warning/error about unused macros:
```
home/runner/work/mmotd/mmotd/common/assertion/src/throw.cpp:153:1: error: macro "__OPTIMIZE__" is not used [-Werror=unused-macros]
  153 | } // namespace mmotd::assertion
      | ^
```